from .dg_text_input import TextInput
from .dg_range_slider_stretching import HistogramManipulationStretching
from .dg_range_slider_pothresholding import PointOperationThresholding
from .dg_range_slider_posterization import PointOperationPosterization
from .dg_blurring import Blurring
from .dg_edge_detection import EdgeDetection
from .dg_linear_sharpening import LinearSharpening
from .dg_universal_mask import UniversalMask